apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  DB_HOST: order-db
  DB_NAME: order_db
  DB_USER: order_db_user
  DB_PASS: order_db_password

  USER_SERVICE_URL: "http://user-service:80"
  PRODUCT_SERVICE_URL: "http://product-service:80"