apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DB_HOST: auth-db
  DB_NAME: auth_db
  DB_USER: auth_db_user
  DB_PASS: auth_db_password
  SECRET_KEY: mysecretkey

  USER_SERVICE_URL: "http://user-service:80"