apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicas }}
  revisionHistoryLimit: {{ .Values.ui.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
        - name: {{ .Values.ui.name }}
          image: "{{ .Values.ui.image }}::{{ .Values.ui.tag }}"
          imagePullPolicy: {{ .Values.ui.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.port }}