apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.product.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.product.env.DB_HOST }}
  DB_NAME: {{ .Values.product.env.DB_NAME }}
  DB_USER: {{ .Values.product.env.DB_USER }}
  DB_PASS: {{ .Values.product.env.DB_PASS }}