apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
    
      initContainers:
      - name: db-migration
        image: user-service:latest
        imagePullPolicy: Never  
        command: ["python", "migrate.py"] 
        envFrom:
        - secretRef:
            name: user-secret

      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: user-secret