apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.order.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.order.name }}
spec:
  type: {{ .Values.order.service.type }}
  selector:
    app: {{ .Values.order.name }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.port }}